version: '3.8'

services:
    api:
        restart: unless-stopped
        container_name: htmlrender-api
        image: htmlrender-api
        ports:
            - 8080:8080
        depends_on:
            - rabbitmq
    renderer:
        restart: unless-stopped
        container_name: htmlrender-renderer
        image: htmlrender-renderer
        security_opt: 
            - seccomp=chrome.json
        depends_on:
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3
        restart: unless-stopped
        container_name: htmlrender-rabbitmq