version: '3.8'

services:
    api:
        restart: unless-stopped
        image: froogo/htmlrender-api
        ports:
            - 8080:8080
        depends_on:
            - rabbitmq
    renderer:
        restart: unless-stopped
        image: froogo/htmlrender-renderer
        deploy:
            mode: replicated
            replicas: 3
        security_opt: 
            - seccomp=chrome.json
        depends_on:
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3
        restart: unless-stopped
        container_name: htmlrender-rabbitmq